# Generated by Django 3.0.6 on 2020-05-15 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogmodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 14, 46, 0, 554609)),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
