# Generated by Django 3.0.6 on 2020-05-16 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200516_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 16, 14, 16, 29, 373219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
