# Generated by Django 3.0.6 on 2020-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='images',
            new_name='image',
        ),
    ]
